version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'p@55w0rd'
      MYSQL_USER: 'local-mysql'
      MYSQL_PASSWORD: 'p@55w0rd'
      MYSQL_DATABASE: 'app'
      MYSQL_TCP_PORT: 3306
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - my-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/www/app
      - /www/app/node_modules
    command: /bin/sh -c "npm run start:dev"
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql-data:
  logs:
